<?php
return [
    'paginate'          => '10',
    'date_search'       => 'Y-m-d',
    'date_show'         => 'd/m/Y',
    'datetime'          => 'd/m/Y H:i',
    'datetime_db'       => 'Y/m/d H:i',
    'yes'               => '1',
    'no'                => '0',
    'percents'          => '100',
    'hour'              => 60,
    'decimal'           => 1,
    'sunday'            => 0,
    'saturday'          => 6,
    'overtime'          => [
        'registered'    => '1',
        'admin_approve' => '2',
        'approved'      => '3',
        'confirm'       => '4',
        'admin_confirm' => '5',
        'confirmed'     => '6',
        'rejected'      => '7',
        'cancel'        => '8',
    ],

    'time' => 'H:i',
    'date_img' => 'Y/m/d',
    'remotes' => [
        'pending' => '1',
        'approved' => '2',
        'rejected' => '3',
        'cancelled' => '4',
    ],
    'position' => [
        'staff' => '1',
        'po' => '2',
        'lead' => '3',
        'culi' => '4',
    ],
    'gender' => [
        'male' => '1',
        'female' => '2',
    ],
    'contract' => [
        'probationary' => '1',
        'staff' => '2',
        'intern' => '3',
    ],
    'status_user' => [
        'active' => '1',
        'inactive' => '2',
    ],
    'role' => [
        'admin' => '1',
        'member' => '2',
        'accounter' => '3',
        'hr' => '4',
        'po' => '5',
    ],
    'add_minutes' => '10',
    'random' => '10',
];
